import { CATALOG, songById, type Song } from '../data/catalog';
import scheduleData from '../data/schedule.json';

/** Day #1 of 27.GUESSR. The archive never goes further back than this. */
export const EPOCH = '2026-01-01';
const DAY_MS = 86_400_000;
const TIMEZONE = 'Europe/Warsaw';

interface ScheduledDay {
  day: number;
  date: string;
  bag: number;
  id: string;
  title: string;
}

/**
 * The committed day-by-day running order, generated by
 * scripts/build-schedule.mjs.
 *
 * It is a file rather than a calculation on purpose. Deriving the order by
 * shuffling the catalog at run time meant one new release reshuffled every
 * day — including days already played — so archives and shared results
 * silently stopped matching between players. The file is append-only: new
 * songs land on days that have not happened yet, and published days never
 * move.
 */
const SCHEDULE = scheduleData.days as ScheduledDay[];

/** Last day the committed schedule covers. Re-run `npm run schedule` before this. */
export const SCHEDULE_END = SCHEDULE.length;

const plDate = new Intl.DateTimeFormat('en-CA', {
  timeZone: TIMEZONE,
  year: 'numeric',
  month: '2-digit',
  day: '2-digit',
});

/**
 * The civil date in Poland as YYYY-MM-DD, so the puzzle rolls over at Polish
 * midnight no matter where the player is.
 */
export function warsawDate(at: Date = new Date()): string {
  return plDate.format(at);
}

/** Whole days between two YYYY-MM-DD dates, counted at UTC noon to dodge DST. */
function daysBetween(from: string, to: string): number {
  const a = Date.parse(`${from}T12:00:00Z`);
  const b = Date.parse(`${to}T12:00:00Z`);
  return Math.round((b - a) / DAY_MS);
}

/** Day 1 is the epoch itself. */
export function dateToDay(date: string): number {
  return daysBetween(EPOCH, date) + 1;
}

export function dayToDate(day: number): string {
  return new Date(Date.parse(`${EPOCH}T12:00:00Z`) + (day - 1) * DAY_MS)
    .toISOString()
    .slice(0, 10);
}

export function todayDay(at: Date = new Date()): number {
  return dateToDay(warsawDate(at));
}

/**
 * The song for a given day, straight from the schedule.
 *
 * Two things can send it to the fallback: a day past the generated horizon, or
 * a scheduled song that has since left the catalog (pulled from the store).
 * Neither should ever take the game down, so both degrade to a stable pick
 * derived from the day number.
 */
export function songForDay(day: number): Song {
  const entry = SCHEDULE[day - 1];
  if (entry) {
    const song = songById(entry.id);
    if (song) return song;
    if (import.meta.env.DEV) {
      console.warn(`[27.guessr] day ${day} points at missing song ${entry.id} (${entry.title})`);
    }
  } else if (import.meta.env.DEV) {
    console.warn(
      `[27.guessr] day ${day} is past the schedule (ends at day ${SCHEDULE_END}) — run: npm run schedule`,
    );
  }
  const n = CATALOG.length;
  return CATALOG[((day % n) + n) % n];
}

/** A random song for practice mode, avoiding the ids passed in where possible. */
export function randomSong(exclude: readonly string[] = []): Song {
  const pool = CATALOG.filter((s) => !exclude.includes(s.id));
  const from = pool.length > 0 ? pool : CATALOG;
  return from[Math.floor(Math.random() * from.length)];
}

const plLong = new Intl.DateTimeFormat('pl-PL', {
  day: 'numeric',
  month: 'long',
  year: 'numeric',
  timeZone: 'UTC',
});

/** "6 września 2026" */
export function formatDay(day: number): string {
  return plLong.format(new Date(`${dayToDate(day)}T12:00:00Z`));
}
